In [3]:
import numpy as np
import torch

In [4]:
t = np.array([[0, 1, 2], [0, 1, 2], [0, 1, 42]])
print(t)

[[ 0  1  2]
 [ 0  1  2]
 [ 0  1 42]]


In [5]:
t = torch.FloatTensor([0, 3, 6])
print(t)

tensor([0., 3., 6.])


In [13]:
t2 = torch.FloatTensor([[3], [1], [2]])
t.matmul(t2)

tensor([15.])